### ISSUE TITLE
Add lua-imagick

### ISSUE THREAD

**Issue by isage** [bungle/awesome-resty#1]
I've finally wrote documentation for it, so could you please add https://github.com/isage/lua-imagick to image formats?

**Comment by bungle** [comment]
Thanks, I added this.

**Comment by isage** [comment]
Oops, i forgot to alter description. I've dropped GraphicsMagick support some time ago, so now it's only ImageMagick bindings

**Comment by bungle** [comment]
Thanks, I fixed it.
