### ISSUE TITLE
add a simple lua template

### ISSUE THREAD

**Issue by lloydzhou** [bungle/awesome-resty#3]
there's one simple lua template can using in lua5.1 and ngx_lua.
https://github.com/lloydzhou/lua-resty-template

i have copy some code from https://github.com/dannote/lua-template, and change the api method and add more features.
1. can change tags
2. write template like "PHP"
3. support cache the compiled template
4. support reduce space in template.

**Comment by bungle** [comment]
I know it, it is already linked in alternatives. It is rather similar to those already mentioned. Most Lua templating engines run just fine with ngx_lua. Maybe I will add it but then again, should I add all the others as well.

**Comment by bungle** [comment]
Is there particular reason why you decided to name your library `lua-resty-template`? Meaning these two cannot be installed the same time:
1. https://github.com/lloydzhou/lua-resty-template
2. https://github.com/bungle/lua-resty-template

**Comment by lloydzhou** [comment]
i have see most lua library named "lua-resty-*", so named it "ua-resty-template".
i don't known how to handle the conflict. :sweat:

**Comment by bungle** [comment]
You could rename you library something else, like lua-resty-simpletemplate (and rename that template.lua to simpletemplate.lua). Or you can pick any other name that some other project isn't already using (of course I don't own that name, I'm just kindly asking you to change it, I know I cannot force you to do so, :-)). Some choices:
- lua-resty-tmpl
- lua-resty-stemplate
- lua-resty-simpletemplate
- lua-resty-dzhoumplate
- lua-resty-pigeon

If you do that, I do promise to add to this list. It is a good templating engine that @dannote has written, and your modifications are fine, even if they make it a little bit more complex (Dan's original idea was to make it simple and tiny as possible while still being powerful, I guess).

**Comment by lloydzhou** [comment]
i like the short name "lua-resty-tmpl"

**Comment by lloydzhou** [comment]
i have change the package name and the file anme.
thanks for you advice!

**Comment by bungle** [comment]
Ok, added now.
