### ISSUE TITLE
Proposing spacewander/lua-resty-mime-sniff

### ISSUE THREAD

**Issue by spacewander** [bungle/awesome-resty#32]
[lua-resty-mime-sniff](https://github.com/spacewander/lua-resty-mime-sniff) is written to sniff real [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) from upload file.
If the repo could  be accepted into awesome-resty, I suggest to place it in a new `Security` section.

**Comment by bungle** [comment]
I added it to utilities.
