### ISSUE TITLE
Delist everything that isn't currently installable with OPM

### ISSUE THREAD

**Issue by rulatir** [bungle/awesome-resty#45]
Please delist everything that isn't currently installable with OPM and requires "strongly discouraged" luarocks.

https://openresty.org/en/using-luarocks.html
https://serverfault.com/questions/961325/recommended-course-of-action-if-package-is-not-in-opm-but-is-in-luarocks-given

**Comment by bungle** [comment]
The `luarocks` is still the de-facto package manager on many OpenResty based projects, and that will not probably change, as those projects probably think that `LuaRocks` is a better fit for them. Some authors publish on both.

**Comment by bungle** [comment]
I am not going to do this, so I close this.
